@startuml
stateDiagram
    [*] --> Ожидание_подхода
    Ожидание_подхода --> Ожидание_нажатия_R: Пользователь подходит к монетке
    Ожидание_нажатия_R --> Сбор_монетки: Пользователь нажимает клавишу "R"
    Сбор_монетки --> Ожидание_подхода: Приложение увеличивает количество монеток
@enduml
