@startuml
sequenceDiagram
    participant User as Пользователь
    participant App as Приложение
    User->>App: Исследование подземелья
    alt Обнаружена_дверь
    App->>User: Сообщение о скрытой двери
    else Нет_двери
    App->>User: Ничего не обнаружено
    end
@enduml
