@startuml
stateDiagram
    [*] --> Ожидание_ввода
    Ожидание_ввода --> Перемещение: Пользователь нажимает стрелочные клавиши
    Перемещение --> Ожидание_ввода: Приложение перемещает персонажа
@enduml
