@startuml
graph TD;
    Start((начало)) --> Move((пользователь нажимает клавишу управления))
    Move -->|Нажата не клавиша управления| End
    Move -->|Нажата клавиша управления| CheckWall(Проверка обнаружения стены)
    CheckWall -->|Обнаружена стена| End
    CheckWall -->|Стены нет| MoveEnd((Персонаж двигается))
@enduml
