@startuml
stateDiagram
    [*] --> Запуск_игры
    Запуск_игры --> Ввод_имени: Пользователь выбирает "Запустить игру" и вводит 1
    Ввод_имени --> Готов_к_началу: Пользователь вводит имя персонажа
    Готов_к_началу --> [*]
@enduml
