name: Python application

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pygame coverage pytest-cov numpy

      - name: Test with pytest
        run: |
          pytest --cov=./ --cov-report=xml --doctest-modules
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml

      - name: Setup Java and SonarScanner
        run: |
          # Install Java 17
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          # Install SonarScanner
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME/sonar-scanner
          export PATH=$HOME/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin:$PATH
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          # Run SonarScanner
          sonar-scanner -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
                        -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
                        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                        -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
          SONAR_PROJECT_KEY: "EgorVarshutin22107_laughing-potato"
          SONAR_ORGANIZATION: "egorvarshutin22107"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
