name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pygame coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest app/test_main.py
        coverage xml
        coverage report

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml

  sonarcloud:
      name: Sona_Cloud
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Install tox and any other packages
          run: pip install tox
        - name: Run-tox
          run: tox -e py
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
              GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: |
                -Dsonar.organization=egorvarshutin22107
                -Dsonar.projectKey=EgorVarshutin22107_laughing-potato
                -Dsonar.python.coverage.reportPaths=coverage.xml